Update docs for the upcoming mixed legacy/spack release
FairRootGroup/FairSoft pull request #337
Opened 2020-10-09 11:54 UTC by ChristianTackeGSI

* Made the main README into a "dispatch" function: Choose your method and continue in another place
* Split up the sections of the spack docs into individual files
* Update the stuff with the status information

Instead of reading the diff, I would recommend to look at the result:
https://github.com/ChristianTackeGSI/FairSoft/blob/pr/docs/README.md

We can either merge this quickly and improve from there or improve the docs part in my pr/docs branch. I am fine with both.

2020-10-09 12:55 UTC, dennisklein requested changes
> We can either merge this quickly and improve from there or improve the docs part in my pr/docs branch. I am fine with both.

Let's merge rather fast and go from there. But please consider my inline comment now.

2020-10-09 12:55 UTC, dennisklein commented on legacy/README.md
> +as relative to the `/legacy/` folder.
```suggestion
Our homegrown bash/cmake based setup system
has been named "Legacy". It has been moved to the
sub-directory `legacy/` to distinguish it clearly
from the future Spack-based setup system
(for more information see [here](../docs/README.md)).
The latter will eventually replace the "Legacy" setup system
in a future release.
```

* I prefer to advertize the upcoming spack-only release "less final". Sure, right now it looks like it is going to be the next release in half a year. But what if we have to release another time in between, which we do not know yet today.
* Let's delete the note on references and rather update such references everywhere please.

2020-10-09 12:59 UTC, dennisklein commented on README.md
> +| This is the homegrown bash/cmake based setup system. | This is an ongoing standardization and modernization effort based on Spack (which itself is still under heavy development). Most things are al
```suggestion
| This is the classic bash/cmake based setup system. | This is an ongoing standardization and modernization effort based on Spack (which itself is still under heavy development). Most things are already working. For early adopters. |
```

2020-10-09 13:28 UTC, ChristianTackeGSI commented
Added requested change.

Also increased quietPeriod a lot.

2020-10-09 13:35 UTC, dennisklein requested changes
Let's make these references more explicit please. Have not looked through the whole document. Please find all of them.

2020-10-09 13:35 UTC, dennisklein commented on legacy/README.md
> +$ ./configure.sh
```suggestion
legacy/$ ./configure.sh
```

2020-10-09 13:35 UTC, dennisklein commented on legacy/README.md
> +found in the current directory of FairSoft from within this directory. If the script is
```suggestion
found in the `legacy/` directory of FairSoft. If the script is
```

2020-10-15 06:59 UTC, dennisklein approved these changes

2020-10-15 06:59 UTC, merged