[legacy] vc: Bump 1.4.4
FairRootGroup/FairSoft pull request #524
Opened 2024-01-29 16:23 UTC by dennisklein

2024-01-29 17:05 UTC, rbx approved these changes

2024-01-29 17:07 UTC, rbx commented
actually, vc download failed. hiccup or something wrong? I'll rerun.

2024-01-29 17:12 UTC, dennisklein commented
Hm, maybe url is wrong.

2024-01-29 17:53 UTC, rbx requested changes

2024-01-29 17:53 UTC, rbx commented on cmake/legacy.cmake
>    URL https://github.com/VcDevel/Vc/releases/download/${vc_version}/Vc-${vc_version}.tar.gz
```suggestion
  URL https://github.com/VcDevel/Vc/archive/refs/tags/${vc_version}.zip
```
🤷‍♂️

2024-01-29 17:54 UTC, rbx commented on cmake/legacy.cmake
>    URL https://github.com/VcDevel/Vc/releases/download/${vc_version}/Vc-${vc_version}.tar.gz
There's only the source code link for this version: https://github.com/VcDevel/Vc/releases/tag/1.4.4
Can we build from that?

2024-01-29 17:55 UTC, rbx commented on cmake/legacy.cmake
>    URL https://github.com/VcDevel/Vc/releases/download/${vc_version}/Vc-${vc_version}.tar.gz
Seems to be the same thing though.

2024-01-30 11:33 UTC, rbx commented on cmake/legacy.cmake
>    URL https://github.com/VcDevel/Vc/releases/download/${vc_version}/Vc-${vc_version}.tar.gz
I've tested this locally and it builds. I'll commit to see how it does on the CI. Can drop if anything is wrong.

2024-01-30 13:39 UTC, rbx approved these changes

2024-01-30 13:43 UTC, merged